### PR TITLE
OM-542 | Add fetch-translations script

### PR DESCRIPTION
**Pull request by Jokinen**
In these changes I've added the generic things you would need for developing JS:

* Test runner (`jest`)
* Linter (`prettier` with defaults, `eslint` with `airbnb-base`)
* CI (`Travis`)

In case all this looks good, I'll make a first release based on this script and write more about current approach into the README (in another PR).

## fetch-translations

This utility allows its user's to fetch translation data from Google sheets. It assumed that the sheets are in a specific format that's understandable for `i18next-json-csv-converter`. The translations are saved into a target file in `JSON` format.

You can use the scrip in two ways. By importing it:

```js
import fetchTranslations from 'helsinki-utils-js/scripts/fetch-translations
```
Or by using package.json scripts:
```bash
fetch-translations <google_sheet_id> -l fi,en,sv -o ./tt
```

**fetchTranslations function**  
`fetchTranslations(sheetId, languages, output[, debug]): Promise`
| Name | Type | Example | Description |
| :- | :- | :- | :- |
|  sheetId | `string` |  | An UUID that represent a google sheet that contains the translations |
| languages | `string[]` | `["en", "fi"]` | Languages that are to be extracted from the sheet |
| output | `string` | `"./src/translations"` | Path to folder where translations should be saved |
| debug | `boolean` |  | When on, the script will log additional details of its progress |

**fetch-translation CLI**  
```bash
Usage: fetch-translation [options] <sheetId>
Options:
  -d, --debug              Output extra debugging
  -l, --languages <items>  Comma separated list of languages to extract
  -o, --output <value>     
  -h, --help               display help for command
```

## More context

Some of CoH projects source translations from Google sheets. @badrange has created a nifty helper script for [kukkuu-ui](https://github.com/City-of-Helsinki/kukkuu-ui). I urge you to check out the original script:

https://github.com/City-of-Helsinki/kukkuu-ui/blob/develop/scripts/update-translations.ts

Other projects wanted to make use of this script, which is why it is now being made available for all. The first project will be [youth-membership-ui](https://github.com/City-of-Helsinki/youth-membership-ui). In this project the script can be taken into use like so:

Install the new dependency
```
npm i https://github.com/City-of-Helsinki/helsinki-utils-js@version
```

Configure `package.json` scripts:
```diff
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "ci": "CI=true yarn test --coverage",
    "lint": "eslint --ext js,ts,tsx src",
+    "update-translations": "fetch-translations 1kvN0olQHdTqsI25yxJucL2Cqq6PXaPjHAkXpKJPjxjU -l fi,en,sv -o ./src/i18n",
    "cypress:open": "cypress open",
```

Run the script
```bash
npm run update-translations
```

In the case where more configurations are needed, a script file may be created in the project, where a developer can import the `fetchTranslations` function and conduct any other config fetching they think is required.

### Motivations for changes

**Why no TypeScript?**  
I've made some alterations to the original script. I've discarded TypeScript and chose to implement the script with an old version of JS syntax. 

**Answer:** The initial version of this library will be published through GitHub, in which case we do not have a package manager where we can build our source, instead we would need to do it in this repository. That would be cumbersome.

**Why the changes in code structure?**  
The original script had a simpler, less nested structure that is likely easier to understand.

**Answer:** I am not sure if it was worth the effort because anticipation is rarely worth it, but I tried to find the ingredients from the original script that would allow the implementation to be more composable. Because this script will be thrown into the wild, on the surface small differences between projects may throw it for a loop. I wanted to create an initial foundation that could be able to facilitate new features without much chafe for existing users.

### CODE REVIEW

**Comment by Jokinen** [comment]
@badrange Didn't come to my mind at all 🤔I trust that you are correct, but what sort of trouble will the file cause?

Is the downside of not having the lockfile small enough where it can be discarded without much concern?

**Comment by badrange** [comment]
From this article I learned a new thing! 

> One thing you might notice when you run this command is that if you already have a package-lock.json it is actually not being bundled. This is because package-lock.json will always be ignored as specified by the list in the npm docs.

> Subsequently this means that if another developer installs your published package, they'll never download your package-lock.json and therefore it will be completely ignored during the installation.

From: 
https://www.twilio.com/blog/lockfiles-nodejs

**Comment by badrange** [comment]
And about Yarn: 
https://medium.com/@ehkasper/should-the-yarn-lock-file-be-committed-in-libraries-6ab475746a6f

**Comment by badrange** [comment]
So I think the conclusion is: We do want the lockfile in the repo, and we do want as liberal requirements in package.json as possible..

**Comment by Jokinen** [comment]
What you quoted is accurate, but here we are installing directly from GitHub, to the project newer gets "packaged" and pacakge-lock.json is not ignored. I checked by looking the at the `node_modules` folder of a project where I had installed the lib.

But I think your other link (and some additional Googling) lays down a case for keeping the file on board. The downside is that lib developers may get a different set of dependencies than lib consumers.

**Pull request merged**
